WebCoiner/Controllers/UserDashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebCoiner;
using System.Threading.Tasks;
using WebCoiner.Models;

namespace WebCoiner.Controllers
{
    [Authorize]
    public class UserDashboardController : Controller
    {
        private Entities db = new Entities();
        private ApplicationUserManager _userManager;


        [ChildActionOnly]
        public  ActionResult getBalanceAsync()
        {
            var user =  UserManager.FindById(User.Identity.GetUserId());
            var list = db.Transactions.Where(x => x.AspNetUser.Id == user.Id && x.Approved == 2).ToList();
            var last = db.GlobalDashboardLists.OrderByDescending(p => p.Id).FirstOrDefault();
            var userDetails = db.AspNetUsers.FirstOrDefault(x => x.Id == user.Id);

            var model = new Dashboard
            {
                BTC = list.Count() != 0 ? list.Sum(x => x.BTC) : 0,
                Tokens = list.Count() != 0 ? list.Sum(x => x.Tokens) : 0,
                Raised = last.Raised,
                InvestmentAmount = userDetails.InvestmentAmount ?? 0,
                CurrentBalance = userDetails.CurrentBalance ?? 0

            };

            return PartialView(model);
        }

        public async Task<ActionResult> Dashboard()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var list = db.Transactions.Where(x => x.AspNetUser.Id == user.Id && x.Approved == 2).ToList();
            var last = db.GlobalDashboardLists.OrderByDescending(p => p.Id).FirstOrDefault();
            var userDetails = db.AspNetUsers.FirstOrDefault(x => x.Id == user.Id);

            var model = new Dashboard
            {
                BTC = list.Count() != 0 ? list.Sum(x => x.BTC) : 0,
                Tokens = list.Count() != 0 ? list.Sum(x => x.Tokens) : 0,
                Raised = last.Raised,
                InvestmentAmount = userDetails.InvestmentAmount ?? 0,
                CurrentBalance = userDetails.CurrentBalance ?? 0

            };

            return View(model);
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: UserDashboard
        public async Task<ActionResult> list()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var transactions = db.Transactions.Where(x => x.AspNetUser.Id == user.Id).Include(t => t.AspNetUser).OrderByDescending(x => x.Id).ToList();
            return View(transactions);
        }

        // GET: UserDashboard/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: UserDashboard/Create
        public async Task<ActionResult> Create(decimal btc = 0)
        {

            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var list = db.Transactions.Where(x => x.AspNetUser.Id == user.Id && x.Approved == 2).ToList();
            var last = db.GlobalDashboardLists.OrderByDescending(p => p.Id).FirstOrDefault();
            var userDetails = db.AspNetUsers.FirstOrDefault(x => x.Id == user.Id);

            var model = new Dashboard
            {
                BTC = list.Count() != 0 ? list.Sum(x => x.BTC) : 0,
                Tokens = list.Count() != 0 ? list.Sum(x => x.Tokens) : 0,
                Raised = last.Raised,
                InvestmentAmount = userDetails.InvestmentAmount ?? 0,
                CurrentBalance = userDetails.CurrentBalance ?? 0
            };
            ViewBag.BTCWallet = db.GlobalDashboardLists.OrderByDescending(p => p.Id).FirstOrDefault().BTCWallet;

            return View(model);

            //ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            //return View(new Transaction { Tokens = (int)(btc * 535000), BTC = btc });
        }

        // POST: UserDashboard/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BTC")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                transaction.UserId = User.Identity.GetUserId();
                transaction.Approved = 0;
                transaction.DateCreated = DateTime.Today;
                transaction.Tokens = (Int32)(transaction.BTC * 535000);

                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("list");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", transaction.UserId);
            return View(transaction);
        }

        //// GET: UserDashboard/Edit/5
        //public ActionResult Edit(int? id)
        //{

        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Transaction transaction = db.Transactions.Find(id);
        //    if (transaction == null && transaction.Approved != 0)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", transaction.UserId);
        //    return View(transaction);
        //}

        //// POST: UserDashboard/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,UserId,DateCreated,Tokens,BTC,Approved")] Transaction transaction)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        Transaction transactionedit = db.Transactions.Find(transaction.Id);
        //        if (transaction == null && transactionedit.Approved != 0)
        //        {
        //            return HttpNotFound();
        //        }

        //        db.Entry(transaction).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("list");
        //    }
        //    ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", transaction.UserId);
        //    return View(transaction);
        //}

        // GET: UserDashboard/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null && transaction.Approved != 0 && transaction.AspNetUser.Id != User.Identity.GetUserId())
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: UserDashboard/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transaction transaction = db.Transactions.Find(id);

            if (transaction == null && transaction.Approved != 0 && transaction.AspNetUser.Id != User.Identity.GetUserId())
            {
                return HttpNotFound();
            }

            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("list");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebCoiner/Views/Shared/_Layout.cshtml
@{
    string controllerName = Request.CurrentExecutionFilePath;
}

@*@model WebCoiner.Models.IndexViewModel
@{
	ViewBag.Title = "Manage";
	var user = Model.AspNetUser.UserName;
}*@

<!DOCTYPE html>

<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


    <title>cibholdings</title>


    <!-- Crypto Admin skins -->
    <!-- Bootstrap 4.0-->
    <link rel="stylesheet" href="~/assets/admin/assets/vendor_components/bootstrap/dist/css/bootstrap.css">

    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/assets/admin/assets/vendor_plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.css">

    <link rel="stylesheet" href="~/assets/admin/css/skin_color.css">


    <!--amcharts -->
    <link href="https://www.amcharts.com/lib/3/plugins/export/export.css" rel="stylesheet" type="text/css" />

    <!-- Data Table-->
    <link rel="stylesheet" type="text/css" href="~/assets/admin/assets/vendor_components/datatable/datatables.min.css" />

    <!-- theme style -->
    <link rel="stylesheet" href="~/assets/admin/css/horizontal-menu.css">
    <link rel="stylesheet" href="~/assets/admin/css/style.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/Content/ico/vendor.bundle.css" id="layoutstyle">
    <link rel="stylesheet" href="~/Content/ico/style.css">
    <link href="~/assets/admin/source/extractcssone.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" />
    <link rel="stylesheet" href="~/assets/login/vendor.bundle.css">
    <link rel="stylesheet" href="~/assets/login/style.css">
    <script src="https://cdn.jsdelivr.net/npm/font-proxima-nova@1.0.1/index.min.js"></script>

    <!--<base href="/">-->

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    @*<script src="~/Content/jquery-1.12.4.min.js"></script>*@

    <script src="~/Scripts/bootstrap.min.js"></script>
</head>

<body class="no-touch layout-top-nav dark-skin theme-classic">
    <app-root>
        <div>
                   <header class="main-header" style="background-color: #1a233a"> 
              <div class="inside-header">
             <div class="d-flex align-items-center logo-box justify-content-between">
            <a href="@Url.Action("Dashboard", "UserDashboard")" class="logo">
                <div class="logo-lg">
                     <span class="navbar-brand">  CIBHOLDINGS  </span> 
                </div>
            </a>
        </div> 
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" style="background-color: #1a233a">
                <!-- Sidebar toggle button-->
                <ul id="main-menu" class="sm sm-blue d-flex justify-content-around">
                    @if (User.IsInRole("administrator"))
                    {
                        <li>
                            <a href="~/dashboard/list/">
                                <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>Dashboard
                            </a>
                        </li>
                        <li>
                            <a href="~/transactions/list">
                                <i class="icon-Equalizer"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></i>Transactions
                            </a>
                        </li>
                        <li>
                            <a href="~/users/list"><i class="icon-Group"><span class="path1"></span><span class="path2"></span></i>Users</a>
                        </li>
                        <li>
                            <a href="~/promocodes/list"><i class="icon-Arrows-h"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i>Promocodes</a>
                        </li>
                        <li>
                            <a href="~/manage/index/"><i class="icon-Chart-line"><span class="path1"></span><span class="path2"></span></i>Profile</a>
                        </li>
                        <li>
                            <a href="~/userdashboard/create/">
                                <i class="icon-Dollar">
                                    <span class="path1"></span>
                                    <span class="path2"></span><span class="path3"></span><span class="path4"></span>
                                </i>Buy Tokens
                            </a>
                        </li>
                        <li>
                            <a href="#" id="modalShow"><i class="icon-Box"><span class="path1"></span><span class="path2"></span></i>Packages</a>
                        </li>
                    }

                    else if (Request.IsAuthenticated)
                    {
                        <li>
                            <a href="~/userdashboard/dashboard/">
                                <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>Dashboard
                            </a>
                        </li>
                        <li>
                            <a href="~/userdashboard/list/"><i class="icon-Equalizer"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></i>Transactions</a>
                        </li>
                        <li>
                            <a href="#"><i class="icon-Chart-pie"><span class="path1"></span><span class="path2"></span></i>ICO</a>
                        </li>
                        <li><a href="currency_exchange.html"><i class="icon-Repeat"><span class="path1"></span><span class="path2"></span></i>Currency</a></li>
                        <li>
                            <a href="~/users/list"><i class="icon-Group"><span class="path1"></span><span class="path2"></span></i>Users</a>
                        </li>
                        <li>
                            <a href="~/promocodes/list"><i class="icon-Arrows-h"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i>Promocodes</a>
                        </li>
                        <li>
                            <a href="~/manage/index/"><i class="icon-Chart-line"><span class="path1"></span><span class="path2"></span></i>Profile</a>
                        </li>
                        <li>
                            <a href="~/userdashboard/create/"><i class="icon-Flower"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></i>Buy Tokens</a>
                        </li>
                        <li>
                            <a href="#"><i class="icon-Bucket"><span class="path1"></span><span class="path2"></span></i>UI</a>
                        </li>
                    }
                    <li class="d-flex align-items-center">
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "" }))
                            {
                                @Html.AntiForgeryToken()
                                <a class="d-flex" href="javascript:document.getElementById('logoutForm').submit()">
                                    <i class="fa fa-cog fa-spin"></i>
                                    <div>Log Out</div>
                                </a>
                            }
                        }
                    </li>
                </ul>

                @*<div class="navbar-custom-menu r-side">
                <ul class="nav navbar-nav">



                </ul>
            </div>*@
            </nav>
                </div>  
             </header> 

            <!-- .navbar -->
        </div><!-- .topbar-wrap -->
        <app-profile>
            @RenderBody()
        </app-profile>
    </app-root>

    @RenderSection("scripts", required: false)

    <script src="~/assets/admin/js/script.js?ver=104"></script>
    <script>

        // Active page menu when click
        var CurURL = window.location.href, urlSplit = CurURL.split("#");
        var $nav_link = $("a");
        if ($nav_link.length > 0) {
            $nav_link.each(function () {
                if (CurURL === (this.href) && (urlSplit[1] !== "")) {
                    $(this).closest("li").addClass("active").parent().closest("li").addClass("active");
                }
            });
        }

        //// Set the date we're counting down to
        //var countDownDate = new Date("jan 01, 2022 00:00:00").getTime();

        //// Update the count down every 1 second
        //var x = setInterval(function () {

        //    // Get todays date and time
        //    var now = new Date().getTime();

        //    // Find the distance between now and the count down date
        //    var distance = countDownDate - now;

        //     //Time calculations for days, hours, minutes and seconds
        //    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        //    $('.countdown-time-first').html(days);
        //    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        //    $('.countdown-time-second').html(hours);
        //    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        //    $('.countdown-time-third').html(minutes);
        //    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
        //    $('.countdown-time-last').html(seconds);
        //}, 1000);
    </script>
    <script type="text/javascript">
        /* When the user clicks on the button,
        toggle between hiding and showing the dropdown content */

        function redirectBack() {
            var url = '@Url.Action("Dashboard", "UserDashboard")';
            window.location.href = url;
        };


        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>


</body>

</html>

WebCoiner/Views/Shared/getBalanceAsync.cshtml
@model WebCoiner.Models.Dashboard


<span class="navbar-text" style="color:#b9b9b9;font-size:13px;    font-family: Open Sans,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif;">
    Avalaibe Tokens <br /> <strong style="color:#ffffff">@Model.Tokens</strong> 
</span>